uploads = []

[[generated]]
id = "MRJMeGBYt_YRscrzLxQZO"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "project manager icon"

[[generated]]
id = "sGEGTrfiVyVtV4qkTXUB2"
uri = "file://artifacts/mobile/assets/images/splash-icon.png"
type = "image"
title = "splash icon"

[[outputs]]
id = "Vqs-d6W72EfcoPu9VNKd4"
uri = "file://exports/divayshakati-data.json"
type = "unspecified"
title = "Divayshakati - Full Data Export (JSON)"

[[outputs]]
id = "oAxGboZjSEW6Wf2JZClKv"
uri = "file://exports/divayshakati-hostinger.tar.gz"
type = "unspecified"
title = "Divayshakati Production Package (Hostinger ke liye)"

[[outputs]]
id = "-r0NV3vlyb3WTo1PXqr78"
uri = "file://exports/divayshakati-hostinger.zip"
type = "unspecified"
title = "Divayshakati - CJS Format (dist/index.js)"
